"""Initial migration

Revision ID: 41c2b10d3b93
Revises: 
Create Date: 2026-04-19 14:29:15.190049

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '41c2b10d3b93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
