"""add summary to chats

Revision ID: 468d157ad0f1
Revises: 41c2b10d3b93
Create Date: 2026-04-23 16:16:35.648772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468d157ad0f1'
down_revision: Union[str, Sequence[str], None] = '41c2b10d3b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('summary', sa.String(length=255), nullable=True))
    op.add_column('chats', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'created_at')
    op.drop_column('chats', 'summary')
    # ### end Alembic commands ###
